### ISSUE TITLE
Error: failed to run custom build command for 'libffi-sys v1.1.0'

### ISSUE THREAD

**Issue by ghost** [meatysolutions/pico-sdk#5]
Hello,

I have recently tried to incorporate this crate into my project and get the following error when building:
```
error: failed to run custom build command for `libffi-sys v1.1.0`

Caused by:
  process didn't exit successfully: `/Users/john/Documents/picoscope/target/debug/build/libffi-sys-553610b39d60f72f/build-script-build` (exit code: 101)
  --- stderr
  autogen.sh: line 2: exec: autoreconf: not found
  thread 'main' panicked at 'Generating configure', /Users/john/.cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-1.1.0/build/common.rs:8:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I have also tried to add `libffi = "1.0.0"` and `libffi-sys = "1.1.0"` to my dependencies list with no luck.

For reference, I am building on macOS with the latest pico-sdk package downloaded from picotech.

Do you have any tips to get this to work? Thank you!

**Comment by timfish** [comment]
The key bit from your error message is:
```
autoreconf: not found
```

Currently this Rust SDK uses `libffi` to work around the fact that some older Pico driver methods do not allow us to pass context with callbacks. `libffi-sys` links to the libffi C library and requires that you have native C build tools installed as well as `automake`, `autoconf`, etc.

To ensure you have C build tools installed, run this in the terminal and follow any prompts:

```shell
xcode-select --install
```

The easiest way to get the other tools installed on macOS is to [install Homebrew](https://docs.brew.sh/Installation) and then run:

```shell
brew install autoconf automake libtool
```

I will add these instructions to the docs/readme!

**Comment by ghost** [comment]
Yep that fixed it. Thank you!

**Comment by timfish** [comment]
I'm going to leave this open to remind me to update the docs!
